Listing media galery
MV-Clouds/EstateXpert-Application pull request #17
Opened 2024-07-10 05:46 UTC by Karan3036

Created the Listing Media Gallery

2024-07-10 12:56 UTC, MRG-MV commented on force-app/main/default/lwc/checkListStatus/checkListStatus.html
> +                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Remove SVG and Path and use Static Resource if possible

2024-07-11 13:24 UTC, MRG-MV requested changes

2024-07-11 13:24 UTC, MRG-MV commented on force-app/main/default/lwc/editCheckListModal/editCheckListModal.js
> +            setTimeout(() => {
Timeout is set as 0 so check if it can work without it or not

2024-07-12 05:52 UTC, Karan3036 commented on force-app/main/default/lwc/checkListStatus/checkListStatus.js
> +        this.objectName = pageRef.attributes.objectApiName;
I have changed the decorators for objectName and recorded.

2024-07-12 06:00 UTC, Karan3036 commented on force-app/main/default/lwc/editCheckListModal/editCheckListModal.js
> +            setTimeout(() => {
If I remove the setTimeout, the scroll bar will not work. That's why I have added the setTimeout.

2024-07-12 08:43 UTC, Karan3036 commented on force-app/main/default/lwc/editCheckListModal/editCheckListModal.js
> +            setTimeout(() => {
Removed the setTimeout out and put the logic into rendered callback.

2024-07-12 08:45 UTC, MRG-MV approved these changes
Approve

2024-07-12 08:45 UTC, merged