EXAPP-103-Marketing-List
MV-Clouds/EstateXpert-Application pull request #23
Opened 2024-07-12 10:48 UTC by vyomsoni

I created a Marketing List component in this branch.

I made the 4 LWC components:-

1) -> marketingListCmp
2) -> marketingListFilterAddCmp
3) -> marketingListFilterCmp
4) -> markeitngListTileView

2 Apex classes :-

1) -> MarketingListCmpController
2) -> MarketingListFilterController

1 Custom metadata :-

1) -> MarketingListFilterConfig

1 fieldset on contact object :-

1) -> MarketingListFieldSet

2024-07-19 10:31 UTC, MRG-MV commented on force-app/main/default/classes/MarketingListFilterController.cls
> +        MVEX__MarketingListFilterConfig__mdt filterConfig = [SELECT MVEX__StaticFields__c FROM MVEX__MarketingListFilterConfig__mdt LIMIT 1];
CRUD permission before SOWL/DML missing.

2024-07-19 11:19 UTC, MRG-MV commented on force-app/main/default/lwc/marketingListCmp/marketingListCmp.js
> +            }, 0);
Change this don't use settimeout ask Karan Singh for help on this if you don't get a solution

2024-07-19 11:19 UTC, MRG-MV commented on force-app/main/default/lwc/marketingListCmp/marketingListCmp.js
> +            }, 0);
Change this don't use settimeout ask Karan Singh for help on this if you don't get a solution

2024-07-19 13:05 UTC, MRG-MV requested changes
Make requested changes

2024-07-19 13:05 UTC, MRG-MV commented on force-app/main/default/lwc/marketingListTileView/marketingListTileView.js
> +    set contactsdata(value) {
use @api decorater and api methods for this to get updated data from the parent

2024-07-19 13:05 UTC, MRG-MV commented on force-app/main/default/lwc/marketingListTileView/marketingListTileView.js
> +        setTimeout(() => {
remove set time out

2024-07-19 13:05 UTC, MRG-MV commented on force-app/main/default/lwc/marketingListTileView/marketingListTileView.js
> +            setTimeout(() => {
remove set timeout

2024-07-29 09:57 UTC, MRG6804 approved these changes

2024-07-29 09:58 UTC, merged